name: CI
on:
  pull_request:
    branches:
      - main
    
jobs:
  run-staging-workflow:
    runs-on: ubuntu-latest
    env:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      GCR_PIPELINE_IMAGE_NAME: ${{ secrets.GCR_PIPELINE_IMAGE_NAME }}
      KUBEFLOW_USERNAME: ${{ secrets.KUBEFLOW_STAGING_USERNAME }}
      KUBEFLOW_PASSWORD: ${{ secrets.KUBEFLOW_STAGING_PASSWORD }}
      KUBEFLOW_NAMESPACE: ${{ secrets.KUBEFLOW_STAGING_NAMESPACE }}
      ZENML_USERNAME: ${{ secrets.ZENML_USERNAME }}
      ZENML_PASSWORD: ${{ secrets.ZENML_PASSWORD }}
      ZENML_HOST: ${{ secrets.ZENML_HOST }}
      ZENML_DEBUG: true
      ZENML_ANALYTICS_OPT_IN: false
      ZENML_LOGGING_VERBOSITY: INFO
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
        
      - id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Authenticate docker
        run: |
          gcloud auth configure-docker --project zenml-demos
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: 'requirements-staging.txt'

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        with:
          requirement_files: 'requirements-staging.txt'
          
      - name: Install requirements
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: |
          pip install -r requirements-staging.txt

      # - name: Install google-auth 2.13.0
      #   run: |
      #     pip install google-auth==2.13.0

      - name: Install wkhtmltopdf
        run: sudo apt-get install wkhtmltopdf

      - name: Connect to ZenML server
        run: |
          zenml connect --no-verify-ssl --url $ZENML_HOST --username $ZENML_USERNAME --password $ZENML_PASSWORD

      - name: Set stack
        run: |
          zenml stack set gcp_gitflow_stack
          zenml stack up

      - name: Pull previous image for caching
        run: |
          docker pull $GCR_PIPELINE_IMAGE_NAME:gitflow_training_pipeline
        continue-on-error: true

      - name: Run pipeline
        run: |
          python run.py \
            --pipeline train \
            --requirements requirements-staging.txt \
            --model iris_classifier

      - name: Read training report
        id: report
        uses: juliangruber/read-file-action@v1
        with:
          path: ./model_train_results.md

      - name: PR comment with training report
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ${{ steps.report.outputs.content }}