name: local
on:
  pull_request:
    branches:
      - main
    
jobs:
  run-local-training-workflow:
    runs-on: ubuntu-latest
    env:
      ZENML_DEBUG: true
      ZENML_ANALYTICS_OPT_IN: false
      ZENML_LOGGING_VERBOSITY: INFO
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - uses: syphar/restore-virtualenv@v1
        id: cache-virtualenv
        with:
          requirement_files: 'requirements.txt'

      - uses: syphar/restore-pip-download-cache@v1
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        with:
          requirement_files: 'requirements.txt'
          
      - name: Install requirements
        if: steps.cache-virtualenv.outputs.cache-hit != 'true'
        run: |
          pip install -r requirements.txt

      - name: Setup local stack
        run: |
          stacks/setup_local_stack.sh

      - name: Run pipeline
        run: |
          python run.py
